import {
  CategoryItem,
  ProductItem,
  SellerItem,
  UserItem,
  ReviewItem,
  CouponItem,
  OrderRecord,
  AuditLogItem,
} from "../types";

export const DEMO_USERS: UserItem[] = [
  {
    id: "usr_admin_01",
    email: "admin@marketsphere.com",
    name: "Victoria Sterling (Admin)",
    role: "ADMIN",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 100-2000",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "usr_seller_01",
    email: "seller@apextech.com",
    name: "Marcus Vance",
    role: "SELLER",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 234-5678",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-01-05T00:00:00.000Z"),
    sellerProfile: {
      id: "sel_apex_01",
      storeName: "ApexTech Official",
      slug: "apextech-official",
      status: "APPROVED",
    },
  },
  {
    id: "usr_seller_02",
    email: "seller@luminalifestyle.com",
    name: "Elena Rostova",
    role: "SELLER",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 345-6789",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-01-10T00:00:00.000Z"),
    sellerProfile: {
      id: "sel_lumina_01",
      storeName: "Lumina Lifestyle",
      slug: "lumina-lifestyle",
      status: "APPROVED",
    },
  },
  {
    id: "usr_seller_03",
    email: "seller@aerofit.com",
    name: "David Chen",
    role: "SELLER",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 456-7890",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-01-15T00:00:00.000Z"),
    sellerProfile: {
      id: "sel_aerofit_01",
      storeName: "AeroFit Dynamics",
      slug: "aerofit-dynamics",
      status: "APPROVED",
    },
  },
  {
    id: "usr_seller_pending",
    email: "seller@ecosphere.com",
    name: "Amara Johnson",
    role: "SELLER",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 567-8901",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-02-01T00:00:00.000Z"),
    sellerProfile: {
      id: "sel_ecosphere_01",
      storeName: "EcoSphere Organics",
      slug: "ecosphere-organics",
      status: "PENDING",
    },
  },
  {
    id: "usr_customer_01",
    email: "alex.customer@example.com",
    name: "Alex Mercer",
    role: "CUSTOMER",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80",
    phone: "+1 (555) 987-6543",
    isEmailVerified: true,
    isActive: true,
    createdAt: new Date("2026-01-20T00:00:00.000Z"),
  },
];

export const DEMO_SELLERS: SellerItem[] = [
  {
    id: "sel_apex_01",
    userId: "usr_seller_01",
    storeName: "ApexTech Official",
    slug: "apextech-official",
    logo: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    description: "Premier creator of high-performance computing, audio gears, and smart wearables.",
    phone: "+1 (555) 234-5678",
    email: "seller@apextech.com",
    address: "100 Silicon Way, San Jose, CA 95110",
    taxId: "US-94-3829104",
    bankAccount: "Chase ****4920",
    status: "APPROVED",
    commissionRate: 8.5,
    rating: 4.9,
    reviewCount: 412,
    createdAt: new Date("2026-01-05T00:00:00.000Z"),
    user: { name: "Marcus Vance", email: "seller@apextech.com" },
    verifications: [
      {
        id: "ver_apex_01",
        documentType: "BUSINESS_LICENSE",
        documentUrl: "https://placehold.co/800x600/png?text=ApexTech+Business+License",
        status: "APPROVED",
      },
    ],
  },
  {
    id: "sel_lumina_01",
    userId: "usr_seller_02",
    storeName: "Lumina Lifestyle",
    slug: "lumina-lifestyle",
    logo: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    description: "Modern minimalist home living, ergonomic furnishings, and culinary essentials.",
    phone: "+1 (555) 345-6789",
    email: "seller@luminalifestyle.com",
    address: "45 Broadway Ave, New York, NY 10006",
    taxId: "US-13-8920194",
    bankAccount: "Wells Fargo ****7712",
    status: "APPROVED",
    commissionRate: 9.0,
    rating: 4.8,
    reviewCount: 285,
    createdAt: new Date("2026-01-10T00:00:00.000Z"),
    user: { name: "Elena Rostova", email: "seller@luminalifestyle.com" },
    verifications: [
      {
        id: "ver_lumina_01",
        documentType: "TAX_ID",
        documentUrl: "https://placehold.co/800x600/png?text=Lumina+Tax+Registration",
        status: "APPROVED",
      },
    ],
  },
  {
    id: "sel_aerofit_01",
    userId: "usr_seller_03",
    storeName: "AeroFit Dynamics",
    slug: "aerofit-dynamics",
    logo: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
    description: "Precision-engineered athletic apparel, recovery systems, and outdoor performance gear.",
    phone: "+1 (555) 456-7890",
    email: "seller@aerofit.com",
    address: "782 Endurance Rd, Boulder, CO 80301",
    taxId: "US-84-7719203",
    bankAccount: "Citibank ****8839",
    status: "APPROVED",
    commissionRate: 10.0,
    rating: 4.9,
    reviewCount: 198,
    createdAt: new Date("2026-01-15T00:00:00.000Z"),
    user: { name: "David Chen", email: "seller@aerofit.com" },
  },
  {
    id: "sel_ecosphere_01",
    userId: "usr_seller_pending",
    storeName: "EcoSphere Organics",
    slug: "ecosphere-organics",
    logo: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=150&q=80",
    banner: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
    description: "Pure botanicals, organic skincare formulations, and sustainable luxury self-care.",
    phone: "+1 (555) 567-8901",
    email: "seller@ecosphere.com",
    address: "12 Green Garden Way, Portland, OR 97201",
    taxId: "US-93-6628190",
    bankAccount: "Bank of America ****2109",
    status: "PENDING",
    commissionRate: 10.0,
    rating: 5.0,
    reviewCount: 0,
    createdAt: new Date("2026-02-01T00:00:00.000Z"),
    user: { name: "Amara Johnson", email: "seller@ecosphere.com" },
    verifications: [
      {
        id: "ver_eco_01",
        documentType: "ORGANIC_CERTIFICATION",
        documentUrl: "https://placehold.co/800x600/png?text=USDA+Organic+Certificate",
        status: "PENDING",
      },
    ],
  },
];

export const DEMO_CATEGORIES: CategoryItem[] = [
  {
    id: "cat_electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Cutting-edge consumer electronics, devices, and innovative gadgets.",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=600&q=80",
    icon: "Laptop",
    isFeatured: true,
    order: 1,
    productCount: 8,
    _count: { products: 8 },
  },
  {
    id: "cat_audio",
    name: "Audio & Sound",
    slug: "audio-sound",
    description: "Audiophile-grade wireless headphones, monitors, and sound systems.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    icon: "Headphones",
    isFeatured: true,
    order: 2,
    productCount: 5,
    _count: { products: 5 },
  },
  {
    id: "cat_home",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Modern minimalist furnishings, culinary equipment, and living decor.",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80",
    icon: "Home",
    isFeatured: true,
    order: 3,
    productCount: 6,
    _count: { products: 6 },
  },
  {
    id: "cat_fitness",
    name: "Fitness & Outdoors",
    slug: "fitness-outdoors",
    description: "Athletic wear, recovery devices, and outdoor expedition gear.",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
    icon: "Activity",
    isFeatured: true,
    order: 4,
    productCount: 5,
    _count: { products: 5 },
  },
  {
    id: "cat_wearables",
    name: "Wearable Tech",
    slug: "wearable-tech",
    description: "Smartwatches, health trackers, and biometric wellness rings.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    icon: "Watch",
    isFeatured: true,
    order: 5,
    productCount: 4,
    _count: { products: 4 },
  },
  {
    id: "cat_smart_home",
    name: "Smart Home",
    slug: "smart-home",
    description: "Automated lighting, smart environmental controls, and security cameras.",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80",
    icon: "Cpu",
    isFeatured: true,
    order: 6,
    productCount: 4,
    _count: { products: 4 },
  },
  {
    id: "cat_computing",
    name: "Computers & Office",
    slug: "computers-office",
    description: "Pro laptops, ultra-wide monitors, mechanical keyboards, and workspace ergonomics.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    icon: "Monitor",
    isFeatured: true,
    order: 7,
    productCount: 5,
    _count: { products: 5 },
  },
  {
    id: "cat_wellness",
    name: "Health & Wellness",
    slug: "health-wellness",
    description: "Botanical self-care, organic formulations, and regenerative nutrition.",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
    icon: "Sparkles",
    isFeatured: true,
    order: 8,
    productCount: 3,
    _count: { products: 3 },
  },
];

export const DEMO_PRODUCTS: ProductItem[] = [
  {
    id: "prod_01",
    title: "ApexBook Pro M3 Max 16-inch",
    slug: "apexbook-pro-m3-max-16-inch",
    headline: "Unrivaled desktop power packed into an ultra-slim aluminum unibody chassis.",
    description: "Engineered for elite software developers, 3D artists, and video professionals. Powered by the groundbreaking 16-core processor with 40-core GPU, Liquid Retina XDR display with ProMotion 120Hz, and up to 22 hours of continuous battery longevity.",
    sku: "APX-NB-M3-16",
    basePrice: 2499.00,
    salePrice: 2299.00,
    costPrice: 1750.00,
    stockQuantity: 45,
    reservedQuantity: 3,
    lowStockThreshold: 10,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: true,
    flashDealEnd: new Date("2026-12-31T23:59:59Z"),
    avgRating: 4.9,
    reviewCount: 128,
    totalSales: 410,
    categoryId: "cat_computing",
    sellerId: "sel_apex_01",
    tags: "laptop, computing, pro, m3, retina, developer",
    images: [
      { id: "img_01_1", url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80", alt: "ApexBook Pro 16", isPrimary: true },
      { id: "img_01_2", url: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80", alt: "ApexBook side view", isPrimary: false },
    ],
    category: { id: "cat_computing", name: "Computers & Office", slug: "computers-office" },
    seller: { id: "sel_apex_01", storeName: "ApexTech Official", slug: "apextech-official", rating: 4.9 },
    attributes: [
      { name: "Processor", value: "16-Core M3 Max" },
      { name: "Memory", value: "36GB Unified RAM" },
      { name: "Storage", value: "1TB Ultra NVMe" },
      { name: "Display", value: "16.2\" Liquid Retina XDR" },
    ],
    variants: [
      { id: "var_01_1", sku: "APX-NB-M3-16-SLV", name: "Space Silver / 36GB / 1TB", price: 2299.00, stockQuantity: 25, attributes: { Color: "Space Silver", RAM: "36GB", SSD: "1TB" } },
      { id: "var_01_2", sku: "APX-NB-M3-16-BLK", name: "Space Black / 48GB / 2TB", price: 2799.00, stockQuantity: 20, attributes: { Color: "Space Black", RAM: "48GB", SSD: "2TB" } },
    ],
  },
  {
    id: "prod_02",
    title: "Apex Acoustic Horizon ANC Headphones",
    slug: "apex-acoustic-horizon-anc-headphones",
    headline: "Studio reference spatial audio with hybrid adaptive noise cancellation.",
    description: "Immerse yourself in high-fidelity acoustics. Featuring custom 45mm beryllium drivers, 8 beamforming microphones for crystal voice pickup, 40-hour battery reserve, and ultra-soft memory foam earcups trimmed in Italian Nappa leather.",
    sku: "APX-AUD-HORIZON",
    basePrice: 349.00,
    salePrice: 299.00,
    stockQuantity: 120,
    reservedQuantity: 5,
    lowStockThreshold: 15,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: true,
    flashDealEnd: new Date("2026-12-31T23:59:59Z"),
    avgRating: 4.8,
    reviewCount: 215,
    totalSales: 680,
    categoryId: "cat_audio",
    sellerId: "sel_apex_01",
    tags: "headphones, anc, wireless, audio, bluetooth, spatial",
    images: [
      { id: "img_02_1", url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80", alt: "Apex Horizon Headphones", isPrimary: true },
      { id: "img_02_2", url: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80", alt: "Horizon earcups close up", isPrimary: false },
    ],
    category: { id: "cat_audio", name: "Audio & Sound", slug: "audio-sound" },
    seller: { id: "sel_apex_01", storeName: "ApexTech Official", slug: "apextech-official", rating: 4.9 },
    attributes: [
      { name: "Driver Size", value: "45mm Beryllium" },
      { name: "Battery Life", value: "40 Hours ANC On" },
      { name: "Connectivity", value: "Bluetooth 5.4 + USB-C Lossless" },
      { name: "Weight", value: "265g" },
    ],
  },
  {
    id: "prod_03",
    title: "Lumina ErgoPro Executive Standing Desk",
    slug: "lumina-ergopro-executive-standing-desk",
    headline: "Smart dual-motor height adjustable workspace crafted with solid walnut.",
    description: "Reclaim your energy and posture. The Lumina ErgoPro features whisper-quiet dual electric motors, anti-collision gyroscopic sensors, 4 memory height presets with LED touch panel, integrated cable management spine, and sustainable North American solid walnut timber.",
    sku: "LUM-DSK-ERGO-01",
    basePrice: 799.00,
    salePrice: 699.00,
    stockQuantity: 32,
    reservedQuantity: 2,
    lowStockThreshold: 8,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: false,
    avgRating: 4.9,
    reviewCount: 94,
    totalSales: 310,
    categoryId: "cat_home",
    sellerId: "sel_lumina_01",
    tags: "desk, ergonomic, walnut, office, furniture, standing desk",
    images: [
      { id: "img_03_1", url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80", alt: "Lumina Standing Desk", isPrimary: true },
      { id: "img_03_2", url: "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=800&q=80", alt: "Desk top close up", isPrimary: false },
    ],
    category: { id: "cat_home", name: "Home & Kitchen", slug: "home-kitchen" },
    seller: { id: "sel_lumina_01", storeName: "Lumina Lifestyle", slug: "lumina-lifestyle", rating: 4.8 },
    attributes: [
      { name: "Material", value: "Solid North American Walnut" },
      { name: "Height Range", value: "24.5\" to 50.2\"" },
      { name: "Load Capacity", value: "350 lbs (158 kg)" },
      { name: "Warranty", value: "10 Years Limited" },
    ],
  },
  {
    id: "prod_04",
    title: "AeroFit Pulse Biometric Performance Smartwatch",
    slug: "aerofit-pulse-biometric-smartwatch",
    headline: "Titanium aerospace case, sapphire crystal, and real-time VO2 max & ECG tracking.",
    description: "Engineered for elite triathletes and everyday wellness enthusiasts. Equipped with dual-frequency multi-GNSS satellite tracking, continuous optical heart rate, blood oxygen saturation (SpO2), skin temperature sensors, and military-grade 100-meter water resistance.",
    sku: "AER-WCH-PULSE",
    basePrice: 399.00,
    salePrice: 349.00,
    stockQuantity: 85,
    reservedQuantity: 4,
    lowStockThreshold: 12,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: true,
    flashDealEnd: new Date("2026-12-31T23:59:59Z"),
    avgRating: 4.7,
    reviewCount: 162,
    totalSales: 540,
    categoryId: "cat_wearables",
    sellerId: "sel_aerofit_01",
    tags: "smartwatch, fitness, gps, titanium, ecg, running",
    images: [
      { id: "img_04_1", url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80", alt: "AeroFit Pulse Watch", isPrimary: true },
      { id: "img_04_2", url: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80", alt: "Watch on wrist", isPrimary: false },
    ],
    category: { id: "cat_wearables", name: "Wearable Tech", slug: "wearable-tech" },
    seller: { id: "sel_aerofit_01", storeName: "AeroFit Dynamics", slug: "aerofit-dynamics", rating: 4.9 },
    attributes: [
      { name: "Case", value: "Grade 5 Aerospace Titanium" },
      { name: "Water Resistance", value: "10 ATM (100m)" },
      { name: "Battery Life", value: "14 Days Typical Use" },
      { name: "Display", value: "1.4\" AMOLED Sapphire Crystal" },
    ],
  },
  {
    id: "prod_05",
    title: "Lumina Barista Master Precision Espresso Machine",
    slug: "lumina-barista-master-precision-espresso",
    headline: "Commercial dual stainless boiler with PID temperature stability and digital timer.",
    description: "Craft cafe-caliber lattes and rich golden crema at home. Features dual thermo-insulated stainless steel boilers, 58mm commercial portafilter, rotary vane pump, 3-second instant steam burst, and microfoam texturing wand.",
    sku: "LUM-ESP-BARISTA",
    basePrice: 1299.00,
    salePrice: 1149.00,
    stockQuantity: 18,
    reservedQuantity: 1,
    lowStockThreshold: 5,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: false,
    avgRating: 4.9,
    reviewCount: 78,
    totalSales: 195,
    categoryId: "cat_home",
    sellerId: "sel_lumina_01",
    tags: "coffee, espresso, kitchen, barista, latte, cafe",
    images: [
      { id: "img_05_1", url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80", alt: "Lumina Espresso Machine", isPrimary: true },
    ],
    category: { id: "cat_home", name: "Home & Kitchen", slug: "home-kitchen" },
    seller: { id: "sel_lumina_01", storeName: "Lumina Lifestyle", slug: "lumina-lifestyle", rating: 4.8 },
    attributes: [
      { name: "Boiler Type", value: "Dual Stainless Steel with PID" },
      { name: "Portafilter", value: "58mm Commercial Grade" },
      { name: "Pump Pressure", value: "15 Bar Italian Rotary" },
      { name: "Water Tank", value: "2.5 Liters Removable" },
    ],
  },
  {
    id: "prod_06",
    title: "Apex SoundPulse Studio Wireless HiFi Speaker",
    slug: "apex-soundpulse-studio-wireless-speaker",
    headline: "Room-filling 120W acoustic power with dual active subwoofers and AirPlay 2.",
    description: "Audiophile-grade room acoustic calibration with high-resolution 24-bit/192kHz DAC. Stream wirelessly via Wi-Fi 6, Apple AirPlay 2, Spotify Connect, or balanced optical line-in.",
    sku: "APX-SPK-SOUNDPULSE",
    basePrice: 429.00,
    salePrice: 389.00,
    stockQuantity: 60,
    reservedQuantity: 2,
    lowStockThreshold: 10,
    status: "ACTIVE",
    isFeatured: false,
    isFlashDeal: false,
    avgRating: 4.7,
    reviewCount: 88,
    totalSales: 320,
    categoryId: "cat_audio",
    sellerId: "sel_apex_01",
    tags: "speaker, hifi, wireless, audio, airplay, bluetooth",
    images: [
      { id: "img_06_1", url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80", alt: "SoundPulse Speaker", isPrimary: true },
    ],
    category: { id: "cat_audio", name: "Audio & Sound", slug: "audio-sound" },
    seller: { id: "sel_apex_01", storeName: "ApexTech Official", slug: "apextech-official", rating: 4.9 },
  },
  {
    id: "prod_07",
    title: "AeroFit Kinetic Magnetic Resistance Rower",
    slug: "aerofit-kinetic-magnetic-resistance-rower",
    headline: "Whisper-quiet 16-level magnetic rowing machine with fold-away space saver design.",
    description: "Engage 86% of your body musculature with zero joint impact. Features aircraft-grade aluminum rail, ultra-responsive magnetic flywheel, Bluetooth workout telemetry, and tablet holder.",
    sku: "AER-FIT-ROWER-01",
    basePrice: 899.00,
    salePrice: 799.00,
    stockQuantity: 14,
    reservedQuantity: 1,
    lowStockThreshold: 5,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: false,
    avgRating: 4.8,
    reviewCount: 47,
    totalSales: 160,
    categoryId: "cat_fitness",
    sellerId: "sel_aerofit_01",
    tags: "rower, fitness, cardio, gym, workout, exercise",
    images: [
      { id: "img_07_1", url: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80", alt: "AeroFit Rower", isPrimary: true },
    ],
    category: { id: "cat_fitness", name: "Fitness & Outdoors", slug: "fitness-outdoors" },
    seller: { id: "sel_aerofit_01", storeName: "AeroFit Dynamics", slug: "aerofit-dynamics", rating: 4.9 },
  },
  {
    id: "prod_08",
    title: "Apex VisionUltra 34-inch Curved OLED Monitor",
    slug: "apex-visionultra-34-inch-curved-oled-monitor",
    headline: "1800R curve, 175Hz refresh rate, 0.03ms response time, 99.3% DCI-P3 color.",
    description: "The ultimate display for immersive creative mastery and zero-latency competitive gaming. Infinite contrast with true blacks, USB-C 90W single-cable power delivery, and KVM switch.",
    sku: "APX-MON-34-OLED",
    basePrice: 1099.00,
    salePrice: 949.00,
    stockQuantity: 28,
    reservedQuantity: 2,
    lowStockThreshold: 6,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: false,
    avgRating: 4.9,
    reviewCount: 112,
    totalSales: 280,
    categoryId: "cat_computing",
    sellerId: "sel_apex_01",
    tags: "monitor, oled, curved, gaming, 175hz, 4k, display",
    images: [
      { id: "img_08_1", url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80", alt: "Apex Curved OLED", isPrimary: true },
    ],
    category: { id: "cat_computing", name: "Computers & Office", slug: "computers-office" },
    seller: { id: "sel_apex_01", storeName: "ApexTech Official", slug: "apextech-official", rating: 4.9 },
  },
  {
    id: "prod_09",
    title: "Lumina Atmosphere Smart Ambient LED Light Bar",
    slug: "lumina-atmosphere-smart-ambient-light-bar",
    headline: "16 million colors with sync-to-screen RGBIC gradient projection.",
    description: "Transform your home entertainment and workspace setup. Works seamlessly with Apple HomeKit, Alexa, and Google Assistant. Features ultra-responsive sound sync microphone and magnetic mounting.",
    sku: "LUM-LGT-ATMOS",
    basePrice: 89.00,
    salePrice: 69.00,
    stockQuantity: 150,
    reservedQuantity: 8,
    lowStockThreshold: 20,
    status: "ACTIVE",
    isFeatured: false,
    isFlashDeal: true,
    flashDealEnd: new Date("2026-12-31T23:59:59Z"),
    avgRating: 4.6,
    reviewCount: 194,
    totalSales: 740,
    categoryId: "cat_smart_home",
    sellerId: "sel_lumina_01",
    tags: "lighting, rgb, smart home, ambient, desk setup",
    images: [
      { id: "img_09_1", url: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80", alt: "Lumina Light Bar", isPrimary: true },
    ],
    category: { id: "cat_smart_home", name: "Smart Home", slug: "smart-home" },
    seller: { id: "sel_lumina_01", storeName: "Lumina Lifestyle", slug: "lumina-lifestyle", rating: 4.8 },
  },
  {
    id: "prod_10",
    title: "AeroFit ThermoRecovery Percussion Massage Gun",
    slug: "aerofit-thermorecovery-percussion-massage-gun",
    headline: "Heated percussion therapy with 16mm stall amplitude and brushless motor.",
    description: "Dissolve muscle soreness in minutes. Delivers up to 3,200 PPM with 4 temperature heating settings (up to 125°F) for accelerated myofascial release and pre-workout activation.",
    sku: "AER-RCV-GUN",
    basePrice: 199.00,
    salePrice: 159.00,
    stockQuantity: 75,
    reservedQuantity: 3,
    lowStockThreshold: 15,
    status: "ACTIVE",
    isFeatured: false,
    isFlashDeal: false,
    avgRating: 4.8,
    reviewCount: 135,
    totalSales: 450,
    categoryId: "cat_fitness",
    sellerId: "sel_aerofit_01",
    tags: "massage gun, recovery, percussion, fitness, therapy",
    images: [
      { id: "img_10_1", url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80", alt: "Massage Gun", isPrimary: true },
    ],
    category: { id: "cat_fitness", name: "Fitness & Outdoors", slug: "fitness-outdoors" },
    seller: { id: "sel_aerofit_01", storeName: "AeroFit Dynamics", slug: "aerofit-dynamics", rating: 4.9 },
  },
  {
    id: "prod_11",
    title: "Apex CyberKey Pro 75% Mechanical Keyboard",
    slug: "apex-cyberkey-pro-75-mechanical-keyboard",
    headline: "CNC anodized aluminum case, gasket mount, hot-swappable switches, and tri-mode connectivity.",
    description: "Engineered for connoisseurs of tactile typing precision. Features factory-lubed linear switches, sound-dampening poron foam, PBT dye-sub keycaps, and custom OLED display screen.",
    sku: "APX-KB-75-PRO",
    basePrice: 189.00,
    salePrice: 159.00,
    stockQuantity: 95,
    reservedQuantity: 6,
    lowStockThreshold: 15,
    status: "ACTIVE",
    isFeatured: false,
    isFlashDeal: false,
    avgRating: 4.9,
    reviewCount: 158,
    totalSales: 510,
    categoryId: "cat_computing",
    sellerId: "sel_apex_01",
    tags: "keyboard, mechanical, 75%, custom, typing, desk setup",
    images: [
      { id: "img_11_1", url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80", alt: "CyberKey Keyboard", isPrimary: true },
    ],
    category: { id: "cat_computing", name: "Computers & Office", slug: "computers-office" },
    seller: { id: "sel_apex_01", storeName: "ApexTech Official", slug: "apextech-official", rating: 4.9 },
  },
  {
    id: "prod_12",
    title: "Lumina PureAura Smart HEPA Air Purifier",
    slug: "lumina-pureaura-smart-hepa-air-purifier",
    headline: "H13 True HEPA filtration capturing 99.97% of airborne allergens, smoke, and dust.",
    description: "Breathe pristine alpine air indoors. Covers up to 1,200 sq ft in 30 minutes with laser particle PM2.5 air quality sensor, quiet sleep mode at 21dB, and essential oil aromatherapy tray.",
    sku: "LUM-AIR-HEPA",
    basePrice: 229.00,
    salePrice: 189.00,
    stockQuantity: 48,
    reservedQuantity: 2,
    lowStockThreshold: 10,
    status: "ACTIVE",
    isFeatured: true,
    isFlashDeal: false,
    avgRating: 4.8,
    reviewCount: 92,
    totalSales: 340,
    categoryId: "cat_home",
    sellerId: "sel_lumina_01",
    tags: "air purifier, hepa, home, smart home, allergies, clean air",
    images: [
      { id: "img_12_1", url: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80", alt: "Lumina Air Purifier", isPrimary: true },
    ],
    category: { id: "cat_home", name: "Home & Kitchen", slug: "home-kitchen" },
    seller: { id: "sel_lumina_01", storeName: "Lumina Lifestyle", slug: "lumina-lifestyle", rating: 4.8 },
  },
];

export const DEMO_COUPONS: CouponItem[] = [
  {
    id: "cpn_welcome10",
    code: "WELCOME10",
    description: "Welcome discount for new customers",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minSpend: 50,
    maxDiscount: 100,
    usageLimit: 1000,
    usageCount: 142,
    isActive: true,
  },
  {
    id: "cpn_flash20",
    code: "FLASH20",
    description: "Flash deal 20% discount on select categories",
    discountType: "PERCENTAGE",
    discountValue: 20,
    minSpend: 100,
    maxDiscount: 200,
    usageLimit: 500,
    usageCount: 88,
    isActive: true,
  },
  {
    id: "cpn_freeship",
    code: "FREESHIP",
    description: "Free standard delivery on any order",
    discountType: "FIXED_AMOUNT",
    discountValue: 9.99,
    minSpend: 25,
    usageLimit: 2000,
    usageCount: 341,
    isActive: true,
  },
  {
    id: "cpn_apex50",
    code: "APEX50",
    description: "$50 off high-end hardware orders over $500",
    discountType: "FIXED_AMOUNT",
    discountValue: 50.0,
    minSpend: 500,
    usageLimit: 250,
    usageCount: 64,
    isActive: true,
  },
];

export const DEMO_ORDERS: OrderRecord[] = [
  {
    id: "ord_demo_01",
    orderNumber: "MS-2026-98104",
    userId: "usr_customer_01",
    status: "DELIVERED",
    subtotal: 2598.00,
    shippingCost: 0,
    taxAmount: 207.84,
    discountAmount: 259.80,
    totalAmount: 2546.04,
    shippingAddress: {
      fullName: "Alex Mercer",
      street: "742 Evergreen Terrace",
      city: "Seattle",
      state: "WA",
      postalCode: "98101",
      country: "United States",
    },
    shippingMethod: "EXPRESS",
    couponCode: "WELCOME10",
    isGift: false,
    paymentStatus: "SUCCEEDED",
    paymentMethod: "STRIPE_TEST",
    items: [
      {
        id: "itm_01_1",
        orderId: "ord_demo_01",
        productId: "prod_01",
        sellerId: "sel_apex_01",
        title: "ApexBook Pro M3 Max 16-inch",
        sku: "APX-NB-M3-16",
        unitPrice: 2299.00,
        quantity: 1,
        subtotal: 2299.00,
        productImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=300&q=80",
        product: { id: "prod_01", title: "ApexBook Pro M3 Max 16-inch", slug: "apexbook-pro-m3-max-16-inch" },
      },
      {
        id: "itm_01_2",
        orderId: "ord_demo_01",
        productId: "prod_02",
        sellerId: "sel_apex_01",
        title: "Apex Acoustic Horizon ANC Headphones",
        sku: "APX-AUD-HORIZON",
        unitPrice: 299.00,
        quantity: 1,
        subtotal: 299.00,
        productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80",
        product: { id: "prod_02", title: "Apex Acoustic Horizon ANC Headphones", slug: "apex-acoustic-horizon-anc-headphones" },
      },
    ],
    shipment: {
      carrier: "FedEx",
      trackingNumber: "FX-9482-1082-US",
      estimatedDelivery: "Delivered on Feb 28, 2026",
      status: "DELIVERED",
    },
    user: { name: "Alex Mercer", email: "alex.customer@example.com" },
    createdAt: new Date("2026-02-24T14:32:00.000Z"),
    updatedAt: new Date("2026-02-28T18:00:00.000Z"),
  },
  {
    id: "ord_demo_02",
    orderNumber: "MS-2026-98105",
    userId: "usr_customer_01",
    status: "SHIPPED",
    subtotal: 699.00,
    shippingCost: 0,
    taxAmount: 55.92,
    discountAmount: 0,
    totalAmount: 754.92,
    shippingAddress: {
      fullName: "Alex Mercer",
      street: "742 Evergreen Terrace",
      city: "Seattle",
      state: "WA",
      postalCode: "98101",
      country: "United States",
    },
    shippingMethod: "STANDARD",
    isGift: false,
    paymentStatus: "SUCCEEDED",
    paymentMethod: "STRIPE_TEST",
    items: [
      {
        id: "itm_02_1",
        orderId: "ord_demo_02",
        productId: "prod_03",
        sellerId: "sel_lumina_01",
        title: "Lumina ErgoPro Executive Standing Desk",
        sku: "LUM-DSK-ERGO-01",
        unitPrice: 699.00,
        quantity: 1,
        subtotal: 699.00,
        productImage: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=300&q=80",
        product: { id: "prod_03", title: "Lumina ErgoPro Executive Standing Desk", slug: "lumina-ergopro-executive-standing-desk" },
      },
    ],
    shipment: {
      carrier: "UPS",
      trackingNumber: "1Z9999999999999999",
      estimatedDelivery: "Expected in 2 business days",
      status: "IN_TRANSIT",
    },
    user: { name: "Alex Mercer", email: "alex.customer@example.com" },
    createdAt: new Date("2026-03-01T10:15:00.000Z"),
    updatedAt: new Date("2026-03-02T12:00:00.000Z"),
  },
];

export const DEMO_REVIEWS: ReviewItem[] = [
  {
    id: "rev_01",
    productId: "prod_01",
    userId: "usr_customer_01",
    rating: 5,
    title: "Best mobile workstation I have ever owned",
    comment: "Compiles our entire monorepo in under 40 seconds. Battery life genuinely lasts all day without carrying a charger.",
    isVerifiedPurchase: true,
    helpfulVotes: 34,
    createdAt: new Date("2026-02-15T09:00:00Z"),
    user: { name: "Alex Mercer", avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80" },
  },
  {
    id: "rev_02",
    productId: "prod_02",
    userId: "usr_customer_01",
    rating: 5,
    title: "ANC cuts out jet engine rumble completely",
    comment: "Took these on a 14-hour transpacific flight. Phenomenal comfort, zero ear fatigue, and battery was still at 68% after landing.",
    isVerifiedPurchase: true,
    helpfulVotes: 21,
    createdAt: new Date("2026-02-18T14:30:00Z"),
    user: { name: "Sarah Connor", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80" },
  },
];

export const DEMO_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "log_01",
    userId: "usr_admin_01",
    userName: "Victoria Sterling (Admin)",
    action: "SELLER_APPROVED",
    entityType: "Seller",
    entityId: "sel_apex_01",
    details: "Approved vendor onboarding application and business registration",
    ipAddress: "192.168.1.1",
    createdAt: new Date("2026-01-05T10:00:00Z"),
  },
  {
    id: "log_02",
    userId: "usr_admin_01",
    userName: "Victoria Sterling (Admin)",
    action: "COUPON_CREATED",
    entityType: "Coupon",
    entityId: "cpn_welcome10",
    details: "Created WELCOME10 with 10% discount and $50 minimum spend",
    ipAddress: "192.168.1.1",
    createdAt: new Date("2026-01-06T11:20:00Z"),
  },
  {
    id: "log_03",
    userId: "usr_seller_01",
    userName: "Marcus Vance",
    action: "PRODUCT_CREATED",
    entityType: "Product",
    entityId: "prod_01",
    details: "Published ApexBook Pro M3 Max 16-inch to active catalog",
    ipAddress: "172.16.0.4",
    createdAt: new Date("2026-01-08T15:45:00Z"),
  },
];
